"""
Hawk Programming Language — C Transpiler & Compiler
Generates clean, readable C code and compiles it via clang/gcc.
"""

import os
import subprocess
from typing import List, Dict, Tuple, Optional, Any, Set
from hawk.ast_nodes import (
    Stmt, Expr, SetStmt, IndexAssignStmt, PrintStmt, IfStmt, WhileStmt, ForStmt,
    FnDef, ReturnStmt, ExprStmt, ImportStmt,
    NumberExpr, StringExpr, BoolExpr, VarExpr, MatrixLiteral, MatrixIndexExpr,
    TransposeExpr, BinOpExpr, UnaryOpExpr, CallExpr
)


class CTranspiler:
    def __init__(self):
        self.declared_vars = set(["pi", "e"])
        self.var_types: Dict[str, str] = {
            "pi": "double",
            "e": "double"
        }
        self.fn_signatures: Dict[str, Tuple[str, List[str]]] = {}
        self.matrix_counter = 0
        self.runtime_header_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "runtime", "hawk_matrix.h"
        )

    def _find_module(self, raw_path: str, base_dir: str) -> Optional[str]:
        """Search for a .hwk module: local dir -> bundled stdlib -> user stdlib."""
        # 1. Local
        c = os.path.normpath(os.path.join(base_dir, raw_path))
        if os.path.exists(c):
            return c
        if not raw_path.endswith(".hwk"):
            c_hwk = c + ".hwk"
            if os.path.exists(c_hwk):
                return c_hwk
        # 2. Bundled stdlib
        pkg_dir = os.path.dirname(os.path.abspath(__file__))
        for stdlib_dir in [
            os.path.join(pkg_dir, "stdlib"),
            os.path.join(os.path.expanduser("~"), ".pyhawk", "stdlib"),
        ]:
            c = os.path.normpath(os.path.join(stdlib_dir, raw_path))
            if os.path.exists(c):
                return c
            if not raw_path.endswith(".hwk"):
                c_hwk = c + ".hwk"
                if os.path.exists(c_hwk):
                    return c_hwk
        return None

    def resolve_imports(self, stmts: List[Stmt], current_file: Optional[str] = None, visited: Optional[Set[str]] = None) -> List[Stmt]:
        if visited is None:
            visited = set()
            if current_file:
                visited.add(os.path.realpath(current_file))

        base_dir = os.path.dirname(current_file) if current_file else os.getcwd()
        expanded_stmts: List[Stmt] = []

        for s in stmts:
            if isinstance(s, ImportStmt):
                raw_path = s.module_path
                candidate = self._find_module(raw_path, base_dir)

                if not candidate:
                    raise FileNotFoundError(
                        f"Hawk Error: Cannot import '{raw_path}'. "
                        f"File not found in local dir, hawk/stdlib/, or ~/.pyhawk/stdlib/."
                    )

                real_path = os.path.realpath(candidate)
                if real_path in visited:
                    continue
                visited.add(real_path)

                with open(real_path, "r", encoding="utf-8") as f:
                    code = f.read()

                from hawk.lexer import Lexer
                from hawk.parser import Parser
                tokens = Lexer(code).tokenize()
                imported_ast = Parser(tokens).parse()

                # Recursively resolve any nested imports
                sub_expanded = self.resolve_imports(imported_ast, real_path, visited)
                expanded_stmts.extend(sub_expanded)
            else:
                expanded_stmts.append(s)

        return expanded_stmts

    def transpile(self, stmts: List[Stmt], current_file: Optional[str] = None) -> str:
        stmts = self.resolve_imports(stmts, current_file)

        # 1. Collect functions and variables
        fn_nodes: List[FnDef] = []
        main_stmts: List[Stmt] = []

        for s in stmts:
            if isinstance(s, FnDef):
                fn_nodes.append(s)
                # Check return type: bool or double
                ret_type = "double"
                for inner_s in s.body:
                    if isinstance(inner_s, ReturnStmt) and inner_s.value:
                        _, val_t = self.transpile_expr(inner_s.value)
                        if val_t == "bool":
                            ret_type = "bool"
                self.fn_signatures[s.name] = (ret_type, ["double"] * len(s.params))
            else:
                main_stmts.append(s)

        out = []
        out.append("/* Generated by PyHawk Compiler v0.1 */")
        out.append("#include <stdio.h>")
        out.append("#include <stdlib.h>")
        out.append("#include <stdbool.h>")
        out.append("#include <math.h>")
        out.append(f'#include "{self.runtime_header_path}"')
        out.append("")
        out.append("#ifndef M_PI")
        out.append("#define M_PI 3.14159265358979323846")
        out.append("#endif")
        out.append("#define pi M_PI")
        out.append("#define e 2.71828182845904523536")
        out.append("")

        # Function prototypes
        if fn_nodes:
            out.append("/* --- User Function Prototypes --- */")
            for f in fn_nodes:
                ret_t = self.fn_signatures.get(f.name, ("double", []))[0]
                params_c = ", ".join([f"double {p}" for p in f.params]) if f.params else "void"
                out.append(f"{ret_t} {f.name}({params_c});")
            out.append("")

        # Function implementations
        if fn_nodes:
            out.append("/* --- User Function Implementations --- */")
            for f in fn_nodes:
                out.append(self.transpile_fn(f))
                out.append("")

        # Main entry point
        out.append("/* --- Main Program Entry --- */")
        out.append("int main(int argc, char **argv) {")
        for s in main_stmts:
            c_code = self.transpile_stmt(s, indent=1)
            if c_code:
                out.append(c_code)
        out.append("    return 0;")
        out.append("}")

        return "\n".join(out)

    def transpile_fn(self, fn: FnDef) -> str:
        ret_type = self.fn_signatures.get(fn.name, ("double", []))[0]
        params_c = ", ".join([f"double {p}" for p in fn.params]) if fn.params else "void"
        saved_types = dict(self.var_types)
        for p in fn.params:
            self.var_types[p] = "double"

        lines = [f"{ret_type} {fn.name}({params_c}) {{"]
        for s in fn.body:
            lines.append(self.transpile_stmt(s, indent=1))
        default_ret = "false" if ret_type == "bool" else "0.0"
        lines.append(f"    return {default_ret};")
        lines.append("}")

        self.var_types = saved_types
        return "\n".join(lines)

    def transpile_stmt(self, stmt: Stmt, indent: int = 1) -> str:
        pad = "    " * indent

        if isinstance(stmt, SetStmt):
            val_code, val_type = self.transpile_expr(stmt.value)
            already_declared = stmt.name in self.declared_vars
            self.var_types[stmt.name] = val_type
            if already_declared:
                return f"{pad}{stmt.name} = {val_code};"
            self.declared_vars.add(stmt.name)
            if val_type == "Matrix*":
                return f"{pad}Matrix *{stmt.name} = {val_code};"
            elif val_type == "HawkVal":
                return f"{pad}HawkVal {stmt.name} = {val_code};"
            elif val_type in ("const char*", "char*"):
                return f"{pad}const char *{stmt.name} = {val_code};"
            elif val_type == "bool":
                return f"{pad}bool {stmt.name} = {val_code};"
            else:
                return f"{pad}double {stmt.name} = {val_code};"

        if isinstance(stmt, IndexAssignStmt):
            r_code, _ = self.transpile_expr(stmt.row)
            c_code, _ = self.transpile_expr(stmt.column) if stmt.column else ("0", "double")
            val_code, val_t = self.transpile_expr(stmt.value)
            if val_t == "HawkVal":
                val_code = f"hawk_val_to_num({val_code})"
            return f"{pad}matrix_set({stmt.matrix_name}, (int)({r_code}), (int)({c_code}), {val_code});"

        if isinstance(stmt, PrintStmt):
            lines = []
            for e in stmt.expressions:
                e_code, e_type = self.transpile_expr(e)
                if e_type == "Matrix*":
                    lines.append(f"{pad}printf(\"\\n\"); matrix_print({e_code});")
                elif e_type == "HawkVal":
                    lines.append(f"{pad}hawk_val_print({e_code});")
                elif e_type in ("const char*", "char*"):
                    lines.append(f"{pad}printf(\"%s \", {e_code});")
                elif e_type == "bool":
                    lines.append(f"{pad}printf(\"%s \", ({e_code}) ? \"true\" : \"false\");")
                else:
                    lines.append(f"{pad}printf(\"%g \", (double)({e_code}));")
            lines.append(f'{pad}printf("\\n");')
            return "\n".join(lines)

        if isinstance(stmt, ReturnStmt):
            if stmt.value:
                val_code, val_t = self.transpile_expr(stmt.value)
                if val_t == "HawkVal":
                    val_code = f"hawk_val_to_num({val_code})"
                return f"{pad}return {val_code};"
            return f"{pad}return 0.0;"

        if isinstance(stmt, IfStmt):
            cond_code, cond_type = self.transpile_expr(stmt.condition)
            if cond_type == "HawkVal":
                cond_clean = f"hawk_val_to_bool({cond_code})"
            elif cond_code.startswith("(") and cond_code.endswith(")"):
                cond_clean = cond_code[1:-1]
            else:
                cond_clean = cond_code
            lines = [f"{pad}if ({cond_clean}) {{"]
            for s in stmt.then_body:
                lines.append(self.transpile_stmt(s, indent + 1))
            if stmt.else_body:
                lines.append(f"{pad}}} else {{")
                for s in stmt.else_body:
                    lines.append(self.transpile_stmt(s, indent + 1))
            lines.append(f"{pad}}}")
            return "\n".join(lines)

        if isinstance(stmt, WhileStmt):
            cond_code, cond_type = self.transpile_expr(stmt.condition)
            if cond_type == "HawkVal":
                cond_clean = f"hawk_val_to_bool({cond_code})"
            elif cond_code.startswith("(") and cond_code.endswith(")"):
                cond_clean = cond_code[1:-1]
            else:
                cond_clean = cond_code
            lines = [f"{pad}while ({cond_clean}) {{"]
            for s in stmt.body:
                lines.append(self.transpile_stmt(s, indent + 1))
            lines.append(f"{pad}}}")
            return "\n".join(lines)

        if isinstance(stmt, ForStmt):
            init_c = self.transpile_stmt(stmt.init, 0).strip().rstrip(";") if stmt.init else ""
            if stmt.condition:
                cond_c, cond_t = self.transpile_expr(stmt.condition)
                if cond_t == "HawkVal":
                    cond_c = f"hawk_val_to_bool({cond_c})"
                elif cond_c.startswith("(") and cond_c.endswith(")"):
                    cond_c = cond_c[1:-1]
            else:
                cond_c = "1"
            step_c = self.transpile_stmt(stmt.step, 0).strip().rstrip(";") if stmt.step else ""
            lines = [f"{pad}for ({init_c}; {cond_c}; {step_c}) {{"]
            for s in stmt.body:
                lines.append(self.transpile_stmt(s, indent + 1))
            lines.append(f"{pad}}}")
            return "\n".join(lines)

        if isinstance(stmt, ExprStmt):
            code, _ = self.transpile_expr(stmt.expr)
            return f"{pad}{code};"

        return ""

    def transpile_expr(self, expr: Expr) -> Tuple[str, str]:
        """Returns tuple: (C expression code, C type: 'double' | 'Matrix*' | 'const char*' | 'bool')"""
        if isinstance(expr, NumberExpr):
            v = expr.value
            return (f"{v}", "double")

        if isinstance(expr, StringExpr):
            s = expr.value.replace('"', '\\"')
            return (f'"{s}"', "const char*")

        if isinstance(expr, BoolExpr):
            return ("true" if expr.value else "false", "bool")

        if isinstance(expr, VarExpr):
            t = self.var_types.get(expr.name, "double")
            return (expr.name, t)

        if isinstance(expr, MatrixLiteral):
            rows = len(expr.rows)
            cols = len(expr.rows[0]) if rows > 0 else 0
            self.matrix_counter += 1
            arr_name = f"_mat_data_{self.matrix_counter}"
            flat_vals = []
            for r in expr.rows:
                for elem in r:
                    c_elem, _ = self.transpile_expr(elem)
                    flat_vals.append(c_elem)
            vals_str = ", ".join(flat_vals)
            # Matrix instantiation in C
            return (f"matrix_from_array({rows}, {cols}, (double[]){{{vals_str}}})", "Matrix*")

        if isinstance(expr, MatrixIndexExpr):
            m_code, _ = self.transpile_expr(expr.matrix)
            r_code, _ = self.transpile_expr(expr.row)
            c_code, _ = self.transpile_expr(expr.column) if expr.column else ("0", "double")
            return (f"matrix_get({m_code}, (int)({r_code}), (int)({c_code}))", "double")

        if isinstance(expr, TransposeExpr):
            m_code, _ = self.transpile_expr(expr.matrix)
            return (f"matrix_transpose({m_code})", "Matrix*")

        if isinstance(expr, UnaryOpExpr):
            op_code, op_type = self.transpile_expr(expr.operand)
            if expr.op == "-":
                if op_type == "Matrix*":
                    return (f"matrix_scale({op_code}, -1.0)", "Matrix*")
                if op_type == "HawkVal":
                    return (f"hawk_val_sub(hawk_val_num(0.0), {op_code})", "HawkVal")
                return (f"(-({op_code}))", "double")
            if expr.op == "not":
                if op_type == "HawkVal":
                    return (f"(!hawk_val_to_bool({op_code}))", "bool")
                return (f"(!({op_code}))", "bool")

        if isinstance(expr, BinOpExpr):
            l_code, l_type = self.transpile_expr(expr.left)
            r_code, r_type = self.transpile_expr(expr.right)
            op = expr.op

            # Matrix operations
            if l_type == "Matrix*" or r_type == "Matrix*":
                if op == "*":
                    if l_type == "Matrix*" and r_type == "Matrix*":
                        return (f"matrix_mult({l_code}, {r_code})", "Matrix*")
                    if l_type == "Matrix*":
                        r_val = f"hawk_val_to_num({r_code})" if r_type == "HawkVal" else r_code
                        return (f"matrix_scale({l_code}, {r_val})", "Matrix*")
                    l_val = f"hawk_val_to_num({l_code})" if l_type == "HawkVal" else l_code
                    return (f"matrix_scale({r_code}, {l_val})", "Matrix*")
                if op == "+":
                    return (f"matrix_add({l_code}, {r_code})", "Matrix*")
                if op == "-":
                    return (f"matrix_sub({l_code}, {r_code})", "Matrix*")

            # HawkVal dynamic operations
            if l_type == "HawkVal" or r_type == "HawkVal":
                l_hv = l_code if l_type == "HawkVal" else (
                    f"hawk_val_num({l_code})" if l_type == "double" else (
                        f"hawk_val_str({l_code})" if l_type in ("const char*", "char*") else (
                            f"hawk_val_bool({l_code})" if l_type == "bool" else f"hawk_val_matrix({l_code})"
                        )
                    )
                )
                r_hv = r_code if r_type == "HawkVal" else (
                    f"hawk_val_num({r_code})" if r_type == "double" else (
                        f"hawk_val_str({r_code})" if r_type in ("const char*", "char*") else (
                            f"hawk_val_bool({r_code})" if r_type == "bool" else f"hawk_val_matrix({r_code})"
                        )
                    )
                )

                if op == "+": return (f"hawk_val_add({l_hv}, {r_hv})", "HawkVal")
                if op == "-": return (f"hawk_val_sub({l_hv}, {r_hv})", "HawkVal")
                if op == "*": return (f"hawk_val_mult({l_hv}, {r_hv})", "HawkVal")
                if op == "/": return (f"hawk_val_div({l_hv}, {r_hv})", "HawkVal")
                if op == "%": return (f"hawk_val_mod({l_hv}, {r_hv})", "HawkVal")
                if op == "^": return (f"hawk_val_pow({l_hv}, {r_hv})", "HawkVal")

                # Comparisons with HawkVal
                if op == "=":
                    if r_type in ("const char*", "char*"):
                        return (f"hawk_val_eq_str({l_code}, {r_code})", "bool")
                    if l_type in ("const char*", "char*"):
                        return (f"hawk_val_eq_str({r_code}, {l_code})", "bool")
                    if r_type == "double":
                        return (f"hawk_val_eq_num({l_code}, {r_code})", "bool")
                    if l_type == "double":
                        return (f"hawk_val_eq_num({r_code}, {l_code})", "bool")
                    if r_type == "bool":
                        return (f"hawk_val_eq_bool({l_code}, {r_code})", "bool")
                    if l_type == "bool":
                        return (f"hawk_val_eq_bool({r_code}, {l_code})", "bool")
                    return (f"hawk_val_eq({l_hv}, {r_hv})", "bool")

                if op == "!=":
                    if r_type in ("const char*", "char*"):
                        return (f"(!hawk_val_eq_str({l_code}, {r_code}))", "bool")
                    if l_type in ("const char*", "char*"):
                        return (f"(!hawk_val_eq_str({r_code}, {l_code}))", "bool")
                    if r_type == "double":
                        return (f"(!hawk_val_eq_num({l_code}, {r_code}))", "bool")
                    if l_type == "double":
                        return (f"(!hawk_val_eq_num({r_code}, {l_code}))", "bool")
                    if r_type == "bool":
                        return (f"(!hawk_val_eq_bool({l_code}, {r_code}))", "bool")
                    if l_type == "bool":
                        return (f"(!hawk_val_eq_bool({r_code}, {l_code}))", "bool")
                    return (f"(!hawk_val_eq({l_hv}, {r_hv}))", "bool")

                if op == ">": return (f"(hawk_val_to_num({l_hv}) > hawk_val_to_num({r_hv}))", "bool")
                if op == "<": return (f"(hawk_val_to_num({l_hv}) < hawk_val_to_num({r_hv}))", "bool")
                if op == ">=": return (f"(hawk_val_to_num({l_hv}) >= hawk_val_to_num({r_hv}))", "bool")
                if op == "<=": return (f"(hawk_val_to_num({l_hv}) <= hawk_val_to_num({r_hv}))", "bool")
                if op == "and": return (f"(hawk_val_to_bool({l_hv}) && hawk_val_to_bool({r_hv}))", "bool")
                if op == "or": return (f"(hawk_val_to_bool({l_hv}) || hawk_val_to_bool({r_hv}))", "bool")

            # String operations
            if l_type in ("const char*", "char*") or r_type in ("const char*", "char*"):
                if op == "+":
                    l_str = l_code if l_type in ("const char*", "char*") else (
                        f"hawk_num_to_str({l_code})" if l_type == "double" else f"hawk_bool_to_str({l_code})"
                    )
                    r_str = r_code if r_type in ("const char*", "char*") else (
                        f"hawk_num_to_str({r_code})" if r_type == "double" else f"hawk_bool_to_str({r_code})"
                    )
                    return (f"hawk_str_concat({l_str}, {r_str})", "const char*")

                if op == "=":
                    return (f"hawk_str_eq({l_code}, {r_code})", "bool")
                if op == "!=":
                    return (f"(!hawk_str_eq({l_code}, {r_code}))", "bool")

            # Scalar arithmetic
            if op == "+": return (f"({l_code} + {r_code})", "double")
            if op == "-": return (f"({l_code} - {r_code})", "double")
            if op == "*": return (f"({l_code} * {r_code})", "double")
            if op == "/": return (f"({l_code} / {r_code})", "double")
            if op == "%": return (f"hawk_mod({l_code}, {r_code})", "double")
            if op == "^": return (f"pow({l_code}, {r_code})", "double")

            # Comparisons: = in Hawk transpiles to == in C
            if op == "=": return (f"({l_code} == {r_code})", "bool")
            if op == "!=": return (f"({l_code} != {r_code})", "bool")
            if op == ">": return (f"({l_code} > {r_code})", "bool")
            if op == "<": return (f"({l_code} < {r_code})", "bool")
            if op == ">=": return (f"({l_code} >= {r_code})", "bool")
            if op == "<=": return (f"({l_code} <= {r_code})", "bool")
            if op == "and": return (f"({l_code} && {r_code})", "bool")
            if op == "or": return (f"({l_code} || {r_code})", "bool")

        if isinstance(expr, CallExpr):
            # Built-in functions
            if expr.callee == "input":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"hawk_input({arg_code})", "HawkVal")
            if expr.callee == "input_str":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"hawk_input_str({arg_code})", "char*")
            if expr.callee == "input_num":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"hawk_input_num({arg_code})", "double")
            if expr.callee == "det":
                m_code, _ = self.transpile_expr(expr.args[0])
                return (f"matrix_det({m_code})", "double")
            if expr.callee in ("sin", "cos", "tan", "sqrt", "abs", "exp", "log", "round", "floor", "ceil"):
                c_fn = "fabs" if expr.callee == "abs" else expr.callee
                arg_code, arg_t = self.transpile_expr(expr.args[0])
                if arg_t == "HawkVal":
                    arg_code = f"hawk_val_to_num({arg_code})"
                return (f"{c_fn}({arg_code})", "double")
            if expr.callee == "system":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"hawk_system({arg_code})", "double")
            if expr.callee == "shell_output":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"hawk_shell_output({arg_code})", "char*")
            if expr.callee == "os_name":
                return ("hawk_os_name()", "char*")
            if expr.callee == "beep":
                return ("(hawk_beep(), 0.0)", "double")
            if expr.callee == "play_sound":
                arg_code = self.transpile_expr(expr.args[0])[0] if expr.args else '""'
                return (f"(hawk_play_sound({arg_code}), 0.0)", "double")

            # User functions
            args_c = []
            for a in expr.args:
                ac, at = self.transpile_expr(a)
                if at == "HawkVal":
                    args_c.append(f"hawk_val_to_num({ac})")
                else:
                    args_c.append(ac)
            ret_t = self.fn_signatures.get(expr.callee, ("double", []))[0]
            return (f"{expr.callee}({', '.join(args_c)})", ret_t)

        return ("0.0", "double")

    def build_native(self, stmts: List[Stmt], output_binary_path: str, current_file: Optional[str] = None) -> str:
        c_code = self.transpile(stmts, current_file)
        c_temp_file = output_binary_path + ".c"
        with open(c_temp_file, "w", encoding="utf-8") as f:
            f.write(c_code)

        # Compilation via clang
        cmd = [
            "clang",
            "-O3",
            f"-I{os.path.dirname(self.runtime_header_path)}",
            c_temp_file,
            "-o", output_binary_path,
            "-lm"
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"C Compilation Error (clang):\n{res.stderr}")

        return output_binary_path
